name: 'Build and test'
inputs:
  rust-version:
    type: string
    required: true
  solana-version:
    type: string
    required: true
  anchor-version:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Install rust
      uses: ./.github/actions/rust
      with:
        version: ${{ inputs.rust-version }}

    - name: Install solana
      uses: ./.github/actions/solana
      with:
        version: ${{ inputs.solana-version }}

    - name: Install anchor
      uses: ./.github/actions/anchor
      with:
        version: ${{ inputs.anchor-version }}
        rust-version: ${{ inputs.rust-version }}

    - name: Build
      uses: ./.github/actions/build-protocol
      with:
        rust-version: ${{ inputs.rust-version }}

    - name: Unit tests
      shell: bash
      run: cargo test

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 17
        cache: yarn

    - name: Build client
      shell: bash
      run: |
        cd npm-client
        npm install
        npm run build
        cd ..

    - name: Build admin client
      shell: bash
      run: |
        cd npm-admin-client
        npm install
        npm run build
        cd ..

    - name: Anchor tests
      shell: bash
      run: |
        yarn install
        echo "yarn test"
